title: Youtube
owner_name: Napoléon Bonaparte Officiel
github_username: will-w-cheng, kinetekenergy, crownedbison, advikg, rayanesouuuu1234
github_repo: "frontend"
baseurl: "/corsica-frontend"

plugins:
- jekyll-remote-theme
future: true
