title: Youtube
owner_name: Napoléon Bonaparte Officiel
github_username: rayanesouuuu1234
github_repo: "productivity_frontend"
baseurl: "/productivity-frontend"

plugins:
- jekyll-remote-theme
future: true
